import { FileBarChart, Download } from "lucide-react";
import { floodCases } from "../data/mockData";

export default function Reports() {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="font-display text-2xl font-semibold text-slate-100">Reports</h1>
        <p className="text-sm text-slate-400">Generated assessment reports available for download.</p>
      </div>

      <div className="overflow-hidden rounded-xl border border-ink-700 bg-ink-800 shadow-panel">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-ink-700 text-left text-xs uppercase tracking-wide text-slate-500">
              <th className="px-5 py-3.5 font-medium">Case</th>
              <th className="px-5 py-3.5 font-medium">Generated</th>
              <th className="px-5 py-3.5 font-medium">Generated By</th>
              <th className="px-5 py-3.5 font-medium"></th>
            </tr>
          </thead>
          <tbody>
            {floodCases.map((c) => (
              <tr key={c.caseId} className="border-b border-ink-700/60 hover:bg-ink-700/30">
                <td className="px-5 py-4">
                  <p className="flex items-center gap-2 font-medium text-slate-100">
                    <FileBarChart size={14} className="text-flood-400" /> {c.title}
                  </p>
                  <p className="font-mono text-xs text-slate-500">{c.caseId}</p>
                </td>
                <td className="px-5 py-4 text-slate-400">{c.eventDate}</td>
                <td className="px-5 py-4 text-slate-400">{c.createdBy}</td>
                <td className="px-5 py-4 text-right">
                  <button className="flex items-center gap-1.5 rounded-lg border border-ink-600 px-3 py-1.5 text-xs font-medium text-slate-300 hover:bg-ink-700/50">
                    <Download size={13} /> Download
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
